In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['CGPA','P_SCORE','LPA'])
df

,CGPA,P_SCORE,LPA
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [3]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
model  = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\dell i5 7th\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.get_weights()

[array([[-1.0876588 ,  0.7814547 ],
        [ 0.9094118 ,  0.21428621]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.30844307],
        [-0.27011573]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
new_weights = [np.array([[0.1,0.1]
            ,[0.1,0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [8]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [14]:
model.fit(df.iloc[:,0:-1].values,df['LPA'].values,epochs=100,verbose=1,batch_size=1)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 27.8961
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 27.5803
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 27.2418
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26.9121
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 26.5529
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 26.2175
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 25.8544
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 25.4521
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 25.0446
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 24.6789
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 24.2344
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 23.8419
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 23.4037
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 22.9563
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 22.4588
Epoc

hense the algorithem which we created manually is better then this keras one cause we have same dataset in both model and we initialize same weighs and bias in both algo bu the manuall one got less loss in 100 eopchs whereas the loss of keras model is bigger then  the manuall on same epochs